version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/segu/personalcontainers/sonarr/data:/config 
      - /home/segu/media/tvseries:/data/tvshows 
      - /home/segu/media/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

networks:
  default:
    name: media-network
    external: true