version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/segu/personalcontainers/radarr/data:/config
      - /home/segu/media/movies:/movies #optional
      - /home/segu/media/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

networks:
  default:
    name: media-network
    external: true